server:
  port: 3000
spring:
  application:
    name: user-service
    version: v1
    desc: portal-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: email_username
    password: email_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  cache:
    jcache:
      config: classpath:ehcache.xml
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: google_client_id
            client-secret: google_client_secret
            scope: profile,email
          naver:
            client-id: naver_client_id
            client-secret: naver_client_secret
            redirect_uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization_grant_type: authorization_code
            scope: name,email,profile_image
            client-name: Naver
          kakao:
            client-id: kakao_client_id
            client-secret: kakao_client_secret
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-name: Kakao
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
  datasource:
    dbcp2:
      initial-size: 20
    url: jdbc:mariadb://${MARIA_DB_HOST:127.0.0.1}:${MARIA_DB_PORT:3306}/${MARIA_DB_NAME:test}?createDatabaseIfNotExist=true&allowMultiQueries=true&useSSL=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${MARIA_DB_USERNAME:root}
    password: ${MARIA_DB_PASSWORD:0000}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        storage_engine: innodb
        format_sql: true
        default_batch_fetch_size: 1000
    show-sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-mariadb.sql
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info
  health:
    mail:
      enabled: false
info:
  app:
    name: User Service
    description: 로그인, 회원관리 및 관리자 기능을 제공
file:
  directory: ${user.home}/msa-attach-volume
messages:
  directory: ${file.directory}/messages
token:
  expiration_time: 7200000
  refresh_time: 86400000
  secret: token_secret
ftp:
  enabled: false
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:admin@${eureka.instance.hostname:localhost}:8761/eureka
service-path: ${SERVICE_PATH:}/user-service
